# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
