# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-13 15:10
from __future__ import unicode_literals

from __future__ import absolute_import
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0007_modify_course_daily_metrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedailymetrics',
            options={'ordering': ('-date_for', 'course_id')},
        ),
    ]
