# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-13 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import figures.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('figures', '0008_cdm_meta_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMauMonthlyMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_for', models.DateField()),
                ('course_id', models.CharField(max_length=255)),
                ('mau', models.IntegerField()),
                ('site', models.ForeignKey(default=figures.models.default_site, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ['-date_for'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteMauMonthlyMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_for', models.DateField()),
                ('mau', models.IntegerField()),
                ('site', models.ForeignKey(default=figures.models.default_site, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ['-date_for'],
                'abstract': False,
            },
        ),
    ]
