# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-14 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('figures', '0009_mau_month_metric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursemaumonthlymetrics',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sitemaumonthlymetrics',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='coursemaumonthlymetrics',
            unique_together=set([('site', 'course_id', 'date_for')]),
        ),
        migrations.AlterUniqueTogether(
            name='sitemaumonthlymetrics',
            unique_together=set([('site', 'date_for')]),
        ),
    ]
