# Generated by Django 2.2.15 on 2020-10-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figures', '0011_add_mau_to_site_daily_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelineerror',
            name='error_type',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified data error'), ('GRADES', 'Grades data error'), ('COURSE', 'Course data error'), ('SITE', 'Site data error')], default='UNSPECIFIED', max_length=255),
        ),
    ]
