# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-02 20:16
from __future__ import unicode_literals
from __future__ import absolute_import

from django import VERSION as DJANGO_VERSION
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    if DJANGO_VERSION[0:2] == (1,8):
        dependencies = [
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
            ('sites', '0001_initial'),
            ('figures', '0012_alter_pipelineerror_field'),
        ]
    else:  # Assuming 1.11+
        dependencies = [
            migrations.swappable_dependency(settings.AUTH_USER_MODEL),
            ('sites', '0002_alter_domain_unique'),
            ('figures', '0012_alter_pipelineerror_field'),
        ]

    operations = [
        migrations.CreateModel(
            name='CourseMonthlyActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('month_for', models.DateField(db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month_for', 'site', 'course_id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursemonthlyactiveuser',
            unique_together=set([('site', 'course_id', 'user', 'month_for')]),
        ),
    ]
